In [4]:
import torch as t
from torch import nn
import numpy as np

m = np.ones((8,8))
print(m)
x,y = 1,1
size = 2


print(m[x-size:x+size+1,y-size:y+size+1])

n = np.sum(m[x-size:x+size+1,y-size:y+size+1])
print(n)


# n = np.array([np.sum(m[max(0,i-size):min(8,i+size+1),max(0,j-size):min(8,j+size+1)]) for i in range(8) for j in range(8)]).reshape((8,8))
# print(n)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
[]
0.0


In [16]:
m = np.array([1,2,3,4,0,1,2,0])
m[:-10] = 0
m

array([1, 2, 3, 4, 0, 1, 2, 0])